import os
import re

from osa_tool.config.settings import ConfigLoader
from osa_tool.utils import get_repo_tree, parse_folder_name


class SourceRank:
    """
    SourceRank
    
    SourceRank analyzes a repository's file tree to determine the presence of key
    documentation, testing, and licensing files, and assigns a ranking score based
    on these criteria.
    
    Class Methods:
    - __init__:
    """

    def __init__(self, config_loader: ConfigLoader):
        """
        Initializes the repository explorer with configuration and prepares the repository tree.
        
        Args:
            config_loader: An object that provides access to the configuration data. The
                configuration is expected to expose a `config` attribute containing
                repository information.
        
        Class fields initialized:
            config: The configuration object retrieved from `config_loader`.
            repo_url: The Git repository URL extracted from the configuration.
            repo_path: The absolute path to the local clone of the repository, derived
                by joining the current working directory with the parsed folder name
                from `repo_url`.
            tree: A text representation of the repository's file tree, generated by
                calling `get_repo_tree` on `repo_path`. This representation excludes
                the `.git` directory and files with extensions listed in
                `get_repo_tree`'s exclusion set.
        
        Returns:
            None
        """
        self.config = config_loader.config
        self.repo_url = self.config.git.repository
        self.repo_path = os.path.join(os.getcwd(), parse_folder_name(self.repo_url))
        self.tree = get_repo_tree(self.repo_path)

    def readme_presence(self) -> bool:
        """
        Determine whether a README file is present in the repository tree.
        
        This method searches the repository's file tree for any file named
        ``README`` with an optional extension (e.g., ``README.md`` or
        ``README.txt``). The search is case‑insensitive.
        
        Args:
            self: The instance containing the repository tree.
        
        Returns:
            bool: ``True`` if a README file is found in the tree, otherwise
            ``False``.
        """
        pattern = re.compile(r"\bREADME(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def license_presence(self) -> bool:
        """
        Check whether a license keyword is present in the tree.
        
        This method searches the ``self.tree`` attribute for occurrences of the
        words *LICENSE* or *LICENCE* (case‑insensitive), optionally followed by a
        file extension such as ``.txt`` or ``.md``.  It returns ``True`` if at
        least one match is found, otherwise ``False``.
        
        Args:
            self: The instance whose ``tree`` attribute contains the text to
                search.
        
        Returns:
            bool: ``True`` if a license keyword is found in ``self.tree``,
            otherwise ``False``.
        """
        pattern = re.compile(r"\bLICEN[SC]E(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def examples_presence(self) -> bool:
        """
        Check for presence of example or tutorial content in the repository.
        
        This method searches the repository's tree representation for
        keywords such as "tutorial", "tutorials", "example", "examples",
        "notebook", or "notebooks".  It returns ``True`` if any of these
        words are found, indicating that the repository likely contains
        example code or tutorial material, otherwise ``False``.
        
        Args:
            self: The instance whose ``tree`` attribute contains the
                repository's textual representation.
        
        Returns:
            bool: ``True`` if the repository contains example or tutorial
            content; ``False`` otherwise.
        """
        pattern = re.compile(r"\b(tutorials?|examples|notebooks?)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def docs_presence(self) -> bool:
        """
        Determine whether the tree contains documentation-related terms.
        
            This method searches the instance's `tree` attribute for any of the
            following case‑insensitive keywords: "docs", "documentation",
            "wiki", or "manuals".  It returns ``True`` if at least one match is
            found, otherwise ``False``.
        
            Parameters
            ----------
            self
        
            Returns
            -------
            bool
                ``True`` if a documentation-related keyword is present in
                ``self.tree``; ``False`` otherwise.
        """
        pattern = re.compile(r"\b(docs?|documentation|wiki|manuals?)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def tests_presence(self) -> bool:
        """
        Check for the presence of test-related keywords in the tree.
        
        This method searches the ``tree`` attribute of the instance for
        common test-related terms such as ``tests``, ``testcases``,
        ``unittest``, or ``test_suite``.  It returns ``True`` if any of
        these terms are found, otherwise ``False``.
        
        Args:
            self: The instance whose ``tree`` attribute is examined.
        
        Returns:
            bool: ``True`` if a test-related keyword is present in
            ``self.tree``, otherwise ``False``.
        """
        pattern = re.compile(r"\b(tests?|testcases?|unittest|test_suite)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def citation_presence(self) -> bool:
        """
        Checks whether the document tree contains a citation placeholder.
        
        This method searches the ``self.tree`` attribute for any occurrence of the word
        ``CITATION`` optionally followed by a dot and additional word characters
        (e.g., ``CITATION.foo``).  The search is case‑insensitive.  It returns ``True``
        if at least one match is found, otherwise ``False``.
        
        Args:
            self: The instance whose ``tree`` attribute is searched.
        
        Returns:
            bool: ``True`` if a citation placeholder is present in ``self.tree``,
            otherwise ``False``.
        """
        pattern = re.compile(r"\bCITATION(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def contributing_presence(self) -> bool:
        """
        Check for the presence of contribution documentation files in the repository tree.
        
        This method searches the repository's file tree for any file whose name contains the
        substring 'contribut' (case‑insensitive) and ends with one of the extensions
        `.md`, `.rst`, or `.txt`. If such a file is found, the method returns ``True``;
        otherwise it returns ``False``.
        
        Args:
            self: The instance whose ``tree`` attribute holds the repository file paths.
        
        Returns:
            bool: ``True`` if a contribution file is present in the tree, ``False`` otherwise.
        """
        pattern = re.compile(r"\b\w*contribut\w*\.(md|rst|txt)$", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def requirements_presence(self) -> bool:
        """
        Determine whether the parsed tree contains a 'requirements' keyword.
        
            This method searches the instance's `tree` attribute for the word
            "requirements" (case‑insensitive), optionally followed by a dot and
            additional word characters (e.g., "requirements.foo").  It returns
            ``True`` if such a pattern is found, otherwise ``False``.
        
            Parameters
            ----------
            self
        
            Returns
            -------
            bool
                ``True`` if the pattern is present in ``self.tree``, otherwise
                ``False``.
        """
        pattern = re.compile(r"\brequirements(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))
