import pytest

from osa_tool.operations.docs.community_docs_generation.license_generation import LicenseCompiler
from tests.utils.mocks.repo_trees import get_mock_repo_tree


def test_license_already_exists(
    sourcerank_with_repo_tree,
    mock_repository_metadata,
    mock_config_manager,
    caplog,
):
    """
    Tests that the LicenseCompiler logs an info message when a LICENSE file already exists.
    
    This test verifies that the compiler detects an existing LICENSE file in the repository tree and logs an informational message instead of attempting to create a duplicate file. This behavior prevents unnecessary file generation and informs the user that the license is already present.
    
    Args:
        sourcerank_with_repo_tree: Factory fixture to create a SourceRank instance configured with a mock repository tree.
        mock_repository_metadata: Mock repository metadata for the compiler.
        mock_config_manager: Mock configuration manager for the compiler.
        caplog: Pytest fixture for capturing log output.
    
    Returns:
        None
    """
    # Arrange
    repo_tree_data = get_mock_repo_tree("FULL")
    sourcerank = sourcerank_with_repo_tree(repo_tree_data)

    compiler = LicenseCompiler(
        config_manager=mock_config_manager,
        metadata=mock_repository_metadata,
        license_type="mit",
    )
    compiler.sourcerank = sourcerank

    caplog.set_level("INFO")

    # Act
    compiler.run()

    # Assert
    assert "LICENSE file already exists." in caplog.text


def test_license_generated_successfully(
    tmp_path,
    sourcerank_with_repo_tree,
    mock_repository_metadata,
    mock_config_manager,
    caplog,
):
    """
    Tests that a license file is successfully generated by the LicenseCompiler.
    
    This test verifies that when the LicenseCompiler runs with a minimal repository
    tree and MIT license type, it creates a LICENSE file at the expected location.
    The test also checks that the generated file contains the correct copyright
    year and owner from the repository metadata, and that a success log message
    is recorded.
    
    Args:
        tmp_path: A temporary directory path for the test repository.
        sourcerank_with_repo_tree: Factory fixture to create a SourceRank instance
            with a given repository tree. The fixture patches `get_repo_tree` to return
            the provided tree and mocks `parse_folder_name` for isolated testing.
        mock_repository_metadata: Mocked repository metadata containing details
            like owner and creation date.
        mock_config_manager: Mocked configuration manager for the compiler.
        caplog: Pytest fixture for capturing log messages.
    
    Returns:
        None
    
    Why:
    - The test uses a minimal repository tree to isolate the license generation logic
      from unrelated repository complexity.
    - The MIT license type is chosen as a representative example to validate the
      compiler's ability to produce a standard license file.
    - Mocking the repository metadata ensures the test is deterministic and
      independent of external data sources.
    - The success log message is checked to confirm the compiler's internal
      logging behavior, which is part of its operational contract.
    """
    # Arrange
    repo_tree_data = get_mock_repo_tree("MINIMAL")
    sourcerank = sourcerank_with_repo_tree(repo_tree_data)
    sourcerank.repo_path = tmp_path

    compiler = LicenseCompiler(
        config_manager=mock_config_manager,
        metadata=mock_repository_metadata,
        license_type="mit",
    )
    compiler.sourcerank = sourcerank

    caplog.set_level("INFO")

    # Act
    compiler.run()

    # Assert
    license_file = tmp_path / "LICENSE"
    assert license_file.exists()
    assert f"{mock_repository_metadata.created_at[:4]} " f"{mock_repository_metadata.owner}" in license_file.read_text()
    assert "LICENSE has been successfully compiled" in caplog.text


def test_unknown_license_type(
    tmp_path,
    sourcerank_with_repo_tree,
    mock_repository_metadata,
    mock_config_manager,
    caplog,
):
    """
    Tests that an unknown license type raises a KeyError and logs an error message.
    
    This test verifies that the LicenseCompiler fails predictably when given an unrecognized license identifier. It ensures that the error is both raised as a KeyError and logged appropriately, which is critical for debugging and user feedback in the OSA Tool's documentation pipeline.
    
    Args:
        tmp_path: Temporary directory path for the repository.
        sourcerank_with_repo_tree: Factory fixture to create a SourceRank instance with a given repository tree.
        mock_repository_metadata: Mocked repository metadata.
        mock_config_manager: Mocked configuration manager.
        caplog: Pytest fixture for capturing log messages.
    
    Raises:
        KeyError: When the license type cannot be resolved.
    """
    # Arrange
    repo_tree_data = get_mock_repo_tree("MINIMAL")
    sourcerank = sourcerank_with_repo_tree(repo_tree_data)
    sourcerank.repo_path = tmp_path

    unknown_license = "unknown_license"

    compiler = LicenseCompiler(
        config_manager=mock_config_manager,
        metadata=mock_repository_metadata,
        license_type=unknown_license,
    )
    compiler.sourcerank = sourcerank

    caplog.set_level("ERROR")

    # Act
    with pytest.raises(KeyError):
        compiler.run()

    assert f"Couldn't resolve {unknown_license} license type" in caplog.text
