from pathlib import Path

from osa_tool.tools.repository_analysis.dependencies import DependencyExtractor
from osa_tool.tools.repository_analysis.documentation import DocumentationAnalyzer
from osa_tool.tools.repository_analysis.models import RepositoryData
from osa_tool.tools.repository_analysis.testing import TestAnalyzer
from osa_tool.utils.utils import get_repo_tree


class RepositoryAnalyzer:
    """
    RepositoryAnalyzer is a class designed to perform comprehensive analysis on a given code repository.
    
        It extracts various metadata and metrics from the repository, including dependencies, workflows,
        documentation, testing information, and basic file statistics.
    
        Attributes:
            repo_path: Path to the repository being analyzed.
            existing_jobs: A set of job identifiers that already exist.
            tree: A text representation of the repository's file tree, excluding the .git directory.
    
        Methods:
            __init__: Initializes the analyzer with repository path and existing job data.
            analyze: Performs multi-faceted repository analysis and returns structured RepositoryData.
            _count_files_and_lines: Recursively counts Python files and lines of code in the repository.
    """

    def __init__(self, repo_path: str, existing_jobs: set[str]):
        """
        Initializes the repository analyzer instance.
        
        Args:
            repo_path: Path to the repository being analyzed.
            existing_jobs: A set of job identifiers that already exist. This is used to avoid creating duplicate jobs during analysis.
        
        Initializes the following instance attributes:
            repo_path (str): Path to the repository being analyzed.
            existing_jobs (list): A list of job identifiers that already exist. The input set is converted to a list for internal use.
            tree (str): A text representation of the repository's file tree, generated by a helper function. It excludes the .git directory and other non‑source files (like logs, images, binaries) to focus the analysis on relevant source code and documentation.
        """
        self.repo_path = repo_path
        self.existing_jobs = list(existing_jobs)
        self.tree = get_repo_tree(repo_path)

    def analyze(self) -> RepositoryData:
        """
        Analyzes a repository to extract comprehensive metadata and metrics.
        
        This method performs a multi-faceted analysis of a code repository, including
        dependency extraction, workflow examination, documentation assessment, testing
        evaluation, and basic file statistics. It aggregates all findings into a
        structured RepositoryData object.
        
        The analysis uses the repository tree and path stored in the analyzer instance,
        along with any pre‑collected workflow jobs (existing_jobs). This centralizes
        data collection to support automated documentation generation and repository
        enhancement.
        
        Args:
            self: The RepositoryAnalyzer instance containing the repository tree,
                repository path, and pre‑extracted workflow jobs.
        
        Returns:
            RepositoryData: A structured object containing all analysis results,
            including:
                - dependencies: A dictionary with a "python" key mapping to a list of
                  technology names extracted from dependency files.
                - python_version: The Python version requirement extracted from
                  pyproject.toml or setup.py, or None if not found.
                - workflows: The pre‑collected workflow jobs (existing_jobs).
                - documentation: Results from the DocumentationAnalyzer.
                - testing: Results from the TestAnalyzer.
                - total_py_files: Total count of Python files in the repository.
                - total_loc: Total lines of code across all Python files.
                - repo_tree: The repository file tree used for the analysis.
        """
        # Dependency analysis
        dep_extractor = DependencyExtractor(self.tree, self.repo_path)
        dependencies_list = list(dep_extractor.extract_techs())
        dependencies = {"python": dependencies_list}
        python_version = dep_extractor.extract_python_version_requirement()

        # Workflow analysis
        workflows = self.existing_jobs

        # Documentation analysis
        doc_analyzer = DocumentationAnalyzer(self.repo_path, self.tree)
        documentation = doc_analyzer.analyze()

        # Test analysis
        test_analyzer = TestAnalyzer(self.tree, dependencies_list, self.existing_jobs)
        testing = test_analyzer.analyze()

        # Basic stats
        total_files, total_loc = self._count_files_and_lines()

        return RepositoryData(
            dependencies=dependencies,
            python_version=python_version,
            workflows=workflows,
            documentation=documentation,
            testing=testing,
            total_py_files=total_files,
            total_loc=total_loc,
            repo_tree=self.tree,
        )

    def _count_files_and_lines(self):
        """
        Recursively traverses the repository path to calculate the total number of Python files and their cumulative lines of code.
        
        The method searches for all files with a .py extension within the directory specified by self.repo_path. It attempts to read each file to count the lines, ignoring encoding errors or file access issues. This is used to gather basic repository metrics, such as codebase size and file count, which can inform documentation generation and repository analysis.
        
        Args:
            self.repo_path: The root directory path of the repository to be analyzed.
        
        Returns:
            tuple: A tuple containing (total_files, total_loc), where total_files is the count of Python files found and total_loc is the total number of lines across those files.
        """
        total_files, total_loc = 0, 0
        for f in Path(self.repo_path).rglob("*.py"):
            if f.is_file():
                total_files += 1
                try:
                    total_loc += len(f.read_text(encoding="utf-8", errors="ignore").splitlines())
                except Exception:
                    pass
        return total_files, total_loc
