import os
import re

from osa_tool.config.settings import ConfigManager
from osa_tool.utils.utils import get_repo_tree, parse_folder_name


class SourceRank:
    """
    A comprehensive repository analysis system that evaluates and scores project structure, documentation quality, and overall maintainability. It assesses various aspects of code organization, file completeness, and adherence to best practices to provide a holistic view of repository health and readiness for collaboration.
    
        This class inspects the repository file tree and provides
        boolean signals indicating the presence of commonly expected
        project artifacts such as README, LICENSE, documentation,
        examples, tests, and metadata files.
    """


    def __init__(self, config_manager: ConfigManager):
        """
        Initializes the SourceRank repository explorer instance.
        
        Args:
            config_manager: Configuration manager providing access to Git settings. Used to retrieve the repository URL.
        
        Initializes the following class fields:
            repo_url (str): The URL of the Git repository, obtained from the configuration.
            repo_path (str): The local filesystem path to the cloned repository. This is constructed by joining the current working directory with a folder name parsed from the repository URL.
            tree (str): A text representation of the repository's file tree, excluding the `.git` directory and other non-source files. This is generated by scanning the local repository path.
        
        The method sets up the necessary state for exploring and analyzing the repository's structure and contents.
        """
        self.repo_url = config_manager.get_git_settings().repository
        self.repo_path = os.path.join(os.getcwd(), parse_folder_name(self.repo_url))
        self.tree = get_repo_tree(self.repo_path)

    def readme_presence(self) -> bool:
        """
        Checks for the presence of a README file within the repository tree.
        
        This method uses a case-insensitive regular expression to search the object's tree attribute for a file named README, potentially followed by a file extension. The presence of a README file is a common indicator of project documentation and is used in repository quality scoring.
        
        Args:
            self: The instance of the SourceRank class containing the repository tree.
        
        Returns:
            bool: True if a README file is found in the tree, False otherwise.
        """
        pattern = re.compile(r"\bREADME(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def license_presence(self) -> bool:
        """
        Checks for the presence of a license file within the repository tree.
        
        This method uses a regular expression to search the object's tree attribute for common license filenames (e.g., LICENSE, LICENCE) with optional file extensions, performing a case-insensitive match. The presence of a license file is a key indicator of a project's licensing clarity and is used in repository scoring to assess documentation completeness.
        
        Args:
            self: The SourceRank instance containing the repository tree to search.
        
        Returns:
            bool: True if a license file pattern is found in the tree, False otherwise.
        """
        pattern = re.compile(r"\bLICEN[SC]E(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def examples_presence(self) -> bool:
        """
        Checks for the presence of examples, tutorials, or notebooks within the file tree.
        
        This method uses a regular expression to search the instance's tree attribute for keywords indicating the existence of documentation or demonstration files. The check is performed to assess the repository's educational or onboarding support, which contributes to the overall project quality and accessibility score.
        
        Args:
            self: The instance of the SourceRank class containing the tree attribute to be searched.
        
        Returns:
            bool: True if any of the specified keywords (tutorial, tutorials, example, examples, notebook, notebooks) are found in the tree string, False otherwise.
        """
        pattern = re.compile(r"\b(tutorials?|examples|notebooks?)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def docs_presence(self) -> bool:
        """
        Checks for the presence of documentation-related keywords within the tree.
        
        This method uses a regular expression to search for terms such as 'doc', 'docs', 'documentation', 'wiki', or 'manual' within the instance's tree attribute, performing a case-insensitive match. This helps assess whether the repository contains explicit documentation directories or files, which is a factor in evaluating the project's documentation quality and accessibility.
        
        Args:
            self: The instance of the SourceRank class containing the tree attribute to search.
        
        Returns:
            bool: True if a documentation-related keyword is found, False otherwise.
        """
        pattern = re.compile(r"\b(docs?|documentation|wiki|manuals?)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def tests_presence(self) -> bool:
        """
        Checks for the presence of test-related keywords within the source tree.
        
        This method uses a regular expression to search for common testing terminology such as 'test', 'tests', 'testcase', 'testcases', 'unittest', or 'test_suite' within the object's tree attribute. The search is case-insensitive. This check helps assess the project's testing maturity and documentation quality, which are factors in the overall SourceRank scoring.
        
        Args:
            self: The SourceRank instance containing the tree attribute to search.
        
        Returns:
            bool: True if any test-related keywords are found, False otherwise.
        """
        pattern = re.compile(r"\b(tests?|testcases?|unittest|test_suite)\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def citation_presence(self) -> bool:
        """
        Checks for the presence of a citation marker within the tree.
        
        This method uses a regular expression to search for the word "CITATION" (case-insensitive), potentially followed by a file extension, within the object's tree attribute. This is used to identify if the repository includes a citation file (e.g., CITATION, CITATION.txt, CITATION.md), which is important for academic attribution and proper credit in open‑source projects.
        
        Args:
            self: The instance of the SourceRank class.
        
        Returns:
            bool: True if a citation pattern is found, False otherwise.
        """
        pattern = re.compile(r"\bCITATION(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))

    def contributing_presence(self) -> bool:
        """
        Checks for the presence of a contribution guidelines file in the repository tree.
        
        The method uses a regular expression to search the file tree for common filenames 
        associated with contribution instructions, such as CONTRIBUTING.md, 
        contributing.rst, or similar variations. This check is performed to assess 
        repository quality and completeness, as contribution guidelines are important 
        for community engagement and project maintainability.
        
        Args:
            self: The instance of the SourceRank class containing the repository tree.
        
        Returns:
            bool: True if a contributing file matching the pattern is found, False otherwise.
        """
        pattern = re.compile(r"\b\w*contribut\w*\.(md|rst|txt)$", re.IGNORECASE | re.MULTILINE)
        return bool(pattern.search(self.tree))

    def requirements_presence(self) -> bool:
        """
        Checks for the presence of a requirements file within the file tree.
        
        This method uses a regular expression to search the instance's tree attribute for 
        filenames that match the standard requirements pattern (e.g., 'requirements.txt', 
        'requirements.pip', or just 'requirements'), case-insensitively. This check is performed
        to determine if the repository explicitly declares its Python dependencies, which is a
        common indicator of project maturity and ease of setup.
        
        Args:
            self: The instance of the SourceRank class containing the file tree to search.
        
        Returns:
            bool: True if a requirements file pattern is found, False otherwise.
        """
        pattern = re.compile(r"\brequirements(\.\w+)?\b", re.IGNORECASE)
        return bool(pattern.search(self.tree))
